### ISSUE TITLE
Measurements: Cervical vertebra

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#248] opened 2018-08-26 19:56 UTC
Measurements menu needs to be enabled for the cervical vertebra 1-7 (including Cervical vertebra 6/7) @SachinPawaskarUNO

**Comment by SachinPawaskarUNO** [comment] 2018-08-26 20:04
This issue has been fixed and will be available in the upcoming release of CoRA. However I'm reopening this issue as it needs to be verified by DPAA Anthropologists

**Comment by emilystreetman** [comment] 2018-09-25 16:44
This issue is not corrected in cora-cat yet. Also the right menu link to cora-docs does not currently link to the vertebrae section of the measurements guide:

![cervical measurements](https://user-images.githubusercontent.com/34662044/46029122-2c076e00-c0b8-11e8-89bc-00b3e14a9337.jpg)

![cervical measurements2](https://user-images.githubusercontent.com/34662044/46029166-4e998700-c0b8-11e8-8416-cc7317d1e288.jpg)

**Comment by emilystreetman** [comment] 2018-09-26 17:37
Images for measurements are being addressed in ticket #259

**Comment by emilystreetman** [comment] 2018-10-09 15:57
C1 and C2 pages are now active per the original request of this ticket. 

Based on our discussions, I believe the final step before closing this ticket is for @SachinPawaskarUNO to de-activate the measurements pages for Cervical vertebrae 3-7, including cervical vertebra 6/7, since these elements do not have measurements associated. @fedamann, will you please confirm this request?

**Comment by emilystreetman** [comment] 2018-10-09 21:13
Following the scrum on 9OCT18, this request is confirmed by @fedamann . I also double checked, this has not yet been put into CAT.

![image](https://user-images.githubusercontent.com/34662044/46699025-3c523980-cbde-11e8-9604-7c360ab1edd4.png)

**Comment by emilystreetman** [comment] 2018-11-01 17:53
The issue raising in the original ticket has been resolved. Measurements pages are active for C1 and C2 only, with no access to measurements pages of C3-C7. Verified.

**Closed by emilystreetman** 2018-11-01 17:53 UTC
Labels: bug, data, images, v1.0.0
